### ISSUE TITLE
Unable to display the icon for the workspace folders

### ISSUE THREAD

**Issue by LoveWork2021** [catppuccin/vscode-icons#11]
![1](https://user-images.githubusercontent.com/97864775/233955700-b0f19f31-d7b8-4968-995f-c91d9c9fb35d.png)

vscode 1.77.3

**Comment by prazdevs** [comment]
this is the actual icon 😬  maybe i should consider new icons for root folder 🤔

**Comment by LoveWork2021** [comment]
😅This icon does not have the same style as other icons. I thought it was a bug, but couldn't find the cause

**Comment by prazdevs** [comment]
I'll make new ones when I get some time, want them to look different than regular folder icons, but maybe more in the style of the others 😅

**Comment by amwelles** [comment]
perhaps they could be solid, rather than outline style?

**Comment by Alecton4** [comment]
How about a briefcase icon like [this one](https://icon-sets.iconify.design/fluent-mdl2/work/)? Seems briefcase-like icons are not used in our project yet.
