### ISSUE TITLE
Different Icons for Angular File Types

### ISSUE THREAD

**Issue by HarryPoggers** [catppuccin/vscode-icons#110]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

Different types of Angular typescript files are sometimes hard to distinguish due to their very similar naming and them all being typescript files. However, there are standard naming conventions of typescript files and also the HTML, CSS and JS files used to distinguish between them.

### References

![image](https://github.com/catppuccin/vscode-icons/assets/41262691/fb2d35a9-b904-49ef-86c9-832c1bdd3ffb)

**Comment by prazdevs** [comment]
Added multiple angular icons, however for framework-agnostic purpose of the base theme, it requires you to associate them through the custom associations settings in the extension :)
