### ISSUE TITLE
Neovim support

### ISSUE THREAD

**Issue by itsdend** [catppuccin/vscode-icons#111]
### Describe the feature

Will this icons ever be available in Neovim?

**Comment by prazdevs** [comment]
I think this issue belongs in https://github.com/catppuccin/nvim

There is a plan to, one day, make an icon font of the icons in the repo, so it can be used in stuff like nvim. It's still a "plan" and not something existing.

I'll close this one issue and let you create one over the ctp/nvim repo, eventually @ me on that issue or link this one.
