### ISSUE TITLE
add env association for `.env.cat` files

### ISSUE THREAD

**Issue by elijaholmos** [catppuccin/vscode-icons#117]
### Icon

env

### Context and associations

I was working on a project and noticed that many .env filenames were supported, except .env.cat:
![image](https://github.com/catppuccin/vscode-icons/assets/35435704/e6cddf85-569b-491f-8379-cd0416ab2c08)

CAT is comparable to UAT in the how it involves a final level of testing before software is released to production. [Here](https://www.codium.ai/glossary/cat-contract-acceptance-testing/#:~:text=While%20CAT%20revolves%20around%20a,expectations%2C%20needs%2C%20and%20workflow.) is more information about CAT. It is worth noting that .env.uat files have the env association, so this will bring .env.cat files into parity.

**Comment by Krymancer** [comment]
Sorry to commenting in such a old issue but today I noticed that we still have the same behaviour in `.env.nonprod` files I was wondering if we can have the same icon for every `.eny.anyname` or this isn`t a good idea?

**Comment by elijaholmos** [comment]
To be honest, I don't see any reason to only include certain `.env` files in the list of associations. My vote is to associate all `.env.*` files with the "env" file icon.
