### ISSUE TITLE
[Icon Request]: Asciidoc

### ISSUE THREAD

**Issue by thelooter** [catppuccin/vscode-icons#119]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

Asciidoc itself doesn't enfore a file extension, but the most common ones are:
- `.adoc`
- `.asciidoc`
- `.asc`

### References

![image](https://github.com/catppuccin/vscode-icons/assets/24987877/4791e795-920e-4b12-97f0-07c1ddc05d50)
![image](https://github.com/catppuccin/vscode-icons/assets/24987877/70f103af-9b96-40d9-b27f-d363d24f7c29)

**Comment by thelooter** [comment]
Sorry, i couldn't figure out how to resize the images

**Comment by prazdevs** [comment]
nw for the image, should arrive in next release
