### ISSUE TITLE
Add Azure DevOps icons

### ISSUE THREAD

**Issue by iFaxity** [catppuccin/vscode-icons#126]
### Type

- [ ] File icon
- [X] Folder icon

### Context and associations

.azuredevops/

### References

* https://code.benco.io/icon-collection/azure-icons/Azure-DevOps.svg
![image](https://github.com/catppuccin/vscode-icons/assets/9090703/a3a9a1ad-74ff-4bdc-9e65-c8c120123c84)

**Comment by prazdevs** [comment]
added in [1e2ac09](https://github.com/catppuccin/vscode-icons/commit/1e2ac0951320e3812a52bf4b24654cc1f5477c8f)
