### ISSUE TITLE
Gleam language

### ISSUE THREAD

**Issue by FlyinPancake** [catppuccin/vscode-icons#128]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

As gleam reached 1.0.0 it would be great to have icons for its `*.gleam` files and maybe for the `gleam.toml` file.

### References

The projects' homepage: https://gleam.run/

**Comment by uncenter** [comment]
Here's the actual icon they use.
https://gleam.run/images/lucy/lucy.svg:
![](https://gleam.run/images/lucy/lucy.svg)

**Comment by uncenter** [comment]
There are also some cute variations on https://gleam.run/branding/ that could be interesting to use - maybe one icon for .gleam files, the "glowy" or "faded" version for the gleam.toml?

![Screenshot 2024-03-11 at 09 28 18 (Arc)](https://github.com/catppuccin/vscode-icons/assets/47499684/418a2016-eb25-4179-9b5d-10f8e4983c42)

**Comment by uncenter** [comment]
Ooh the faded/dashed one might do good for the `manifest.toml` lockfile (https://gleam.run/writing-gleam/).

**Comment by FlyinPancake** [comment]
Great idea! I'm just a bit worried that the small size of the icons might be unfortunate for the outline
