### ISSUE TITLE
[Icon Request] Ansible Lint

### ISSUE THREAD

**Issue by thelooter** [catppuccin/vscode-icons#129]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

.ansible-lint,
.config/ansible-lint.yml,
.config/ansible-lint.yaml

### References

They don't have their own icon, but the Ansible Icon might be a good place to start from

**Comment by prazdevs** [comment]
Added in [ed5a3fa](https://github.com/catppuccin/vscode-icons/commit/ed5a3faaf2e5ec73220e66cf658ef0ebbf752c85)
