### ISSUE TITLE
Salesforce Apex Icon Request

### ISSUE THREAD

**Issue by ianOsborne** [catppuccin/vscode-icons#131]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

It would be great if we could get an icon for Salesforce's Apex language. The extension ends in .cls

### References

Typically, icons for this file type is just a salesforce cloud logo.
![Microsoft VisualStudio Services Icons](https://github.com/catppuccin/vscode-icons/assets/64973663/42b295b2-4df2-4b3d-84fc-c314f2c896ad)

**Comment by prazdevs** [comment]
added in [6236014](https://github.com/catppuccin/vscode-icons/commit/6236014cc94ea6588b326840ec2172137c9d8735)
