### ISSUE TITLE
Add CSpell icon

### ISSUE THREAD

**Issue by uncenter** [catppuccin/vscode-icons#132]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

- `.cspell.json`
- `cspell.json`
- `.cSpell.json`
- `cSpell.json`
- `cspell.config.js`
- `cspell.config.cjs`
- `cspell.config.json`
- `cspell.config.yaml`
- `cspell.config.yml`
- `cspell.yaml`
- `cspell.yml`

*(from https://cspell.org/configuration/)*

### References

https://cspell.org/favicon.ico:
![](https://cspell.org/favicon.ico)

**Comment by prazdevs** [comment]
added in [1d0f6d5](https://github.com/catppuccin/vscode-icons/commit/1d0f6d51f142b569c68a6a2c23338ec4bf6263f6)
