### ISSUE TITLE
Add Zap Icon

### ISSUE THREAD

**Issue by synpixel** [catppuccin/vscode-icons#133]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

`*.zap`
_(from https://zap.redblox.dev/)_

### References

![image](https://github.com/catppuccin/vscode-icons/assets/110747922/0d9d14f3-3bc6-45d3-ac9c-778be3b49459)

**Comment by prazdevs** [comment]
added in [c5efbdd](https://github.com/catppuccin/vscode-icons/commit/c5efbdde212bf65e018252664a8e4b7527920c2b)
