### ISSUE TITLE
Add humans.txt icon

### ISSUE THREAD

**Issue by uncenter** [catppuccin/vscode-icons#135]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

`humans.txt`

### References

Like the robots.txt icon but with a little human instead? I don't really like the official https://humanstxt.org/ logo...

**Comment by eye-wave** [comment]
![image](https://github.com/catppuccin/vscode-icons/assets/89079979/75d4f01c-4058-4aad-b3aa-4ae0ad9ab43b)
i tried to make one myself, but it's really hard to make it not cluttered while maintaining original design

**Comment by prazdevs** [comment]
Just the "h" without the face would work imo (the outlined 1st version you made @eye-wave )

**Comment by uncenter** [comment]
Closed by #150.
