### ISSUE TITLE
Add Solid icon

### ISSUE THREAD

**Issue by joaopalmeiro** [catppuccin/vscode-icons#137]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

Given that [Solid](https://docs.solidjs.com/) is a framework that also uses JSX, it would be nice to have the possibility of associating its logo with `.jsx` and `.tsx` files in certain projects.

### References

- Solid logo: https://www.solidjs.com/media
- Solid icon by [Tabler Icons](https://github.com/tabler/tabler-icons): https://github.com/tabler/tabler-icons/blob/v3.1.0/icons/outline/brand-solidjs.svg

**Comment by prazdevs** [comment]
added in [bdd6b6e](https://github.com/catppuccin/vscode-icons/commit/bdd6b6e4a33959e3ad2af79f6101e7e6c62f1316)

**Comment by birkskyum** [comment]
I still see this issue in Zed, using catppuccin icon theme. all .jsx/.tsx show up as react, despite lots of frameworks support jsx (preact, solid, vue, etc.)

**Comment by uncenter** [comment]
You can configure the `tsx` extension to use the `solid` icon as documented here: https://github.com/catppuccin/vscode-icons#custom-icon-associations.

```json
	"catppuccin-icons.associations.extensions": {
		"tsx": "solid"
	},
```

(I was going to suggest configuring the `typescriptreact` filetype but it seems there might be a bug in the functionality of that customization feature at the moment.)
