### ISSUE TITLE
.gitmodules file

### ISSUE THREAD

**Issue by thelooter** [catppuccin/vscode-icons#140]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

.gitmodules

### References

maybe the normal git file icon with an added module like the nerdfonts nf-md-view_module icon

**Comment by prazdevs** [comment]
i think the normal git icon is already mapped for this ? trying not to have too many "compound icons" (icons with a main and smaller component like config) as they are visually heavy

**Comment by thelooter** [comment]
Yeah that is fair, it would just make it easier to distinguish the gitmodules file from the gitignore and gitattributes file
