### ISSUE TITLE
Add .tmpl icon

### ISSUE THREAD

**Issue by uncenter** [catppuccin/vscode-icons#148]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

`*.tmpl`

### References

I don't have any references specificaly but something with a mix of the Go icon and the HTML icon maybe? The `.tmpl` is a convention heavily used in the Go ecosystem (https://pkg.go.dev/text/template), for example https://github.com/nishanths/license/tree/master/.templates and most of the projects found through https://github.com/search?q=path:*.tpml&type=code.

**Comment by isabelroses** [comment]
> .gohtml / .go.html
.gotmpl / .go.tmp
.tmpl

https://github.com/microsoft/vscode-go/issues/464#issuecomment-272024047
https://github.com/jinliming2/vscode-go-template/issues/3

**Comment by Miyan0** [comment]
While doing go html icons, `.templ` would be great

[Templ](https://templ.guide/)
