### ISSUE TITLE
Icon Request: CMakeLists.txt, xmake.lua, premake5.lua, *.meson and *.ninja

### ISSUE THREAD

**Issue by CallMeEchoCodes** [catppuccin/vscode-icons#15]
Would be nice for people who dont use makefile.

**Comment by prazdevs** [comment]
should these files use the same icon as current `Makefile` ?

**Comment by CallMeEchoCodes** [comment]
I would love if they had their own logos but its fine if they dont.

* CMake has a logo, all CMake related files and directories should use that logo (Files and dirs include `CMakeLists.txt`, `CMakeFiles/`, `CMakeCache.txt`, etc). CMake logo below

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Cmake.svg/240px-Cmake.svg.png" width="140" height="140" />

* xmake has a logo. `xmake.lua` should use that. xmake logo below
<img src="https://xmake.io/assets/img/logo.svg" width="140" height="140" />

* Premake has a logo. All Premake files should use it (`premake5.lua`, `premake4.lua` and `premake.lua`). Directories called `premake/` should also have the logo. Premake logo below
<img src="https://premake.github.io/img/premake-logo.png" width="140" height="140" />

* Meson has a logo. All `.meson` files should use ir. Meson logo below
<img src="https://avatars.githubusercontent.com/u/12551236?s=200&v=4" width="140" height="140" />

* Ninja does not have a logo but the name lends itself well to a custom icon. I would make a little ninja and use that

**Comment by CallMeEchoCodes** [comment]
you have no idea how long getting all those images took lmao

**Comment by prazdevs** [comment]
I'll do my best to reproduce most of the icons in the theme style. Folders arent a priority tho, so i'll see what i can do when i get some time :)

**Comment by prazdevs** [comment]
it's done, should be live very soon :)
didnt do folders tho, will rethink of it later when i eventually add more

**Comment by CallMeEchoCodes** [comment]
yoo ty! please close the issue when its live :)
