### ISSUE TITLE
v1.12.0 broke my icons

### ISSUE THREAD

**Issue by manc1n1** [catppuccin/vscode-icons#156]
### VSCode/Codium version

VSCode 1.89.0

### Extension version

v1.12.0

### Describe the bug

All my icons disappeared. Restarted VSCode and my laptop multiple times. Downgrading to v1.11.0 solved my problem.

MacBook Pro 2021 M1 Pro Ventura 13.6.6

**Comment by prazdevs** [comment]
I couldnt reproduce and everything works fine on my M1 MBP 🤔 

Maybe was corrupted, and uninstalling/reinstalling the extension completely should fix things
