### ISSUE TITLE
Latest update broke Latte 

### ISSUE THREAD

**Issue by MariuzM** [catppuccin/vscode-icons#163]
### VSCode/Codium version

Latest

### Extension version

v1.13.0

### Describe the bug

<img width="218" alt="image" src="https://github.com/catppuccin/vscode-icons/assets/36937039/c2d48132-7fa5-427d-a1fe-5198a17a93f0">

**Comment by uncenter** [comment]
You said it is broken on latte and then sent a screenshot of something that is not latte. Please provide more information about the bug you are experiencing!

**Comment by MariuzM** [comment]
I'musing latte but screenshot shows its not latter, i tried changing other themes but i keep getting same nothing changes, i have tried restarting vscode nothing.then i installed Catppuccin Perfect Icons and continue your latte and it works so not really sure what was going on

**Comment by uncenter** [comment]
Are we talking about the general theme of VS Code or the theme of just the icons?

**Comment by MariuzM** [comment]
just the icons

**Comment by uncenter** [comment]
I'm unable to reproduce your issue - `Preferences: File Icon Theme` works just fine to change to latte for me.

**Comment by MariuzM** [comment]
i removed the `Catppuccin Perfect Icons` and its working fine now, but really not sure what was happening before

**Comment by prazdevs** [comment]
Sometimes upgrades can break if you have custom associations or settings. Uninstalling and reinstalling should fix it, there's also a "reset" command.
