### ISSUE TITLE
Add Rojo icons

### ISSUE THREAD

**Issue by flxwed** [catppuccin/vscode-icons#165]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

`*.project.json` [Project Files](https://rojo.space/docs/v7/project-format/)
`*.model.json` [JSON Model](https://rojo.space/docs/v7/sync-details/#json-models)
`*.meta.json` [Meta Files](https://rojo.space/docs/v7/sync-details/#meta-files)

### References

![logo-151511d418967797798e02dc0ca74aaf](https://github.com/catppuccin/vscode-icons/assets/29684696/7a0dfb24-ffee-4f4e-aea0-9ed807448a78)

**Comment by prazdevs** [comment]
While i can provide an icon for it, I think adding the associations to files ending in `project.json` or `.model.json` is far too generic and used in all kind of projects, and it would cause confusion.

I'll try to provide an icon, but you will be required to add the associations yourself within the extension settings :)
