### ISSUE TITLE
Add .luaurc icon

### ISSUE THREAD

**Issue by flxwed** [catppuccin/vscode-icons#168]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

`*.luaurc`
Could also consider reusing `luau` icon

### References

https://luau-lang.org/
![luau-88](https://github.com/catppuccin/vscode-icons/assets/29684696/cbf6546e-e5f4-4f9e-a6dc-ada68a1f4c49)

**Comment by lrockreal** [comment]
Could we possibly get a variant with a cog icon underneath for this to differentiate it from a regular `.luau` file?
