### ISSUE TITLE
Icon Request: .j2 Jinja Templates

### ISSUE THREAD

**Issue by thelooter** [catppuccin/vscode-icons#17]
Ansible uses  the Jinja 2 Templates a lot. 
https://palletsprojects.com/p/jinja/

The Logo itself doesn't really lend itself to an Icon, so probably an Icon that just uses j2 as it's text would make most sense

**Comment by prazdevs** [comment]
managed to make a nice icon from the logo

**Comment by prazdevs** [comment]
![image](https://github.com/catppuccin/vscode-icons/assets/1631886/b08fa05b-3cb2-44f7-9dd7-d6d04095d0ad)
 
closing this as it is released :)
