### ISSUE TITLE
Add AutoHotkey icon

### ISSUE THREAD

**Issue by CoffeeChaton** [catppuccin/vscode-icons#174]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

file : ".ahk"
language : "AutoHotkey"

### References

![icon_ahk_v1](https://github.com/catppuccin/vscode-icons/assets/63182963/6c2c93cb-e325-4b9d-91fe-24cbdb033cb9)

**Comment by uncenter** [comment]
You should probably change the title to "Add AutoHotkey icon" to be more clear :)
