### ISSUE TITLE
Assembly icon

### ISSUE THREAD

**Issue by mkukiro** [catppuccin/vscode-icons#18]
hii!! <img src="https://nukocities.neocities.org/nuko/act/cat194.gif">
i've noticed while writing some assembly code that catppuccin doesn't have an icon for it, is it planned? <img src="https://nukocities.neocities.org/nuko/act/cat131.gif">

file extensions for x86 ASM: `.s` `.S` `.asm`

**Comment by prazdevs** [comment]
hi 👋  it's done and live :)
