### ISSUE TITLE
Incompatible

### ISSUE THREAD

**Issue by Starry-Tacos** [catppuccin/vscode-icons#19]
When I try to install this from the marketplace, it says

> Can't install 'catppuccin.catppuccin-vsc-icons' extension because it is not compatible with the current version of Visual Studio Code (version 1.68.0).

```
Equipment:
- Hardware
  - Mac Mini M1 2020
- Software
  - Ventura 13.2.1
  - VSCode
    - Version:  1.68.0 (Universal)
    - Commit:   4af164ea3a06f701fe3e89a2bcbb421d2026b68f
    - OS:       Darwin arm64 22.3.0
```

**Comment by prazdevs** [comment]
You need to upgrade your vscode to at least 1.69.0 (june 2022).
