### ISSUE TITLE
.clang-format file has an incompatible icon

### ISSUE THREAD

**Issue by hububai** [catppuccin/vscode-icons#20]
Hi there! I found the .clang-format file icon type shown as Markdown. Could you check it, plz?

platform: macOS
vscode version: 1.79.0
catppuccin version: v0.16.0

<img width="1436" alt="Screenshot 2023-06-13 at 20 03 24" src="https://github.com/catppuccin/vscode-icons/assets/136082130/1c874ce3-8f9b-4a07-9fcd-9016179ca9d3">

**Comment by hububai** [comment]
Solution: add an association between the **.clang-format** file and the '**properties**' type to help vscode decide which language mode should be used.

``` JSON
{
    "files.associations": {
        ".clang-format": "properties"
    }
}
```

**Comment by prazdevs** [comment]
reopening this, i can add a line of config in the theme to have this natively

**Comment by prazdevs** [comment]
should be done with new release :)
