### ISSUE TITLE
Add Gleam icon

### ISSUE THREAD

**Issue by aslilac** [catppuccin/vscode-icons#207]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

Add an icon for .gleam files for the [Gleam Programming Language](https://gleam.run)

### References

The Gleam VSCode extension adds a default icon, which is just the mascot, Lucy.

**Comment by prazdevs** [comment]
It should exist already since 1.11.0 🤔

**Comment by aslilac** [comment]
oh, my bad! it's not in the readme screenshots, but I shouldn't've assumed that meant it wasn't in the set. hard to keep those updated. 😄

just checked and there is in fact an icon.

**Comment by prazdevs** [comment]
yeah also sometimes github media/previews have some odd cache, you may have older versions back then

**Comment by aslilac** [comment]
....I just thought it was organized alphabetically column first, but it's row first. 😅 sorry for the confusion, thanks for the icon!
