### ISSUE TITLE
Icon request: APL

### ISSUE THREAD

**Issue by mkukiro** [catppuccin/vscode-icons#21]
hello again!! <img src="https://nukocities.neocities.org/nuko/act/cat20.gif">
i've been programming with apl in vscode and then i noticed there is no catppuccin icon for that <img src="https://nukocities.neocities.org/nuko/act/cat342.gif">
it's probably because apl is an obscure language, but it'll be nice if we had an apl icon ^^

file extensions for APL: `.apl`

**Comment by prazdevs** [comment]
should be up in the next release :)
