### ISSUE TITLE
Icon request: Racket

### ISSUE THREAD

**Issue by mkukiro** [catppuccin/vscode-icons#24]
hello!! this will be my last icon request, sorry if i'm stressing everyone out ![](https://nukocities.neocities.org/nuko/react/cat390.gif)
it's for [racket](https://racket-lang.org/), on github, there are ~8.3k repos and ~188k files with racket, so it's not a very obscure language either ![](https://nukocities.neocities.org/nuko/act/cat3.gif)

File extensions: `.rkt` `.rkts` `.rktl` `.rktd` & [full list here!](https://stackoverflow.com/a/52929573/15979865)

**Comment by prazdevs** [comment]
nw, the more icons, the happier people are :)
should be good in the new release

**Comment by mkukiro** [comment]
OMG IT LOOKS PERFECT TYY!!
