### ISSUE TITLE
add `postcss` icon

### ISSUE THREAD

**Issue by Xenos-the-stupid** [catppuccin/vscode-icons#240]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

a javascript config file for postcss, associated with `postcss.config.{js,ts,mjs,cjs}`

### References

![image](https://github.com/user-attachments/assets/ca9aa41e-1ca1-4bd2-bc71-07ca5e358362)

i think it will be cool without the details (tringle circle square, dead simple)

**Comment by uncenter** [comment]
This already exists: https://github.com/catppuccin/vscode-icons/blob/main/icons/latte/postcss.svg.

**Comment by Xenos-the-stupid** [comment]
oh yeah my bad, i think the problem now is that the icon does not appear if the file named `postcss.config.mjs`

**Comment by Xenos-the-stupid** [comment]
i'll close this and open  another bug issue

**Comment by uncenter** [comment]
> i'll close this and open another bug issue

Instead of that you could open a PR fixing it. The code in question is at https://github.com/catppuccin/vscode-icons/blob/5c687f476d2cc3de3dad7f1a754ba27b4213cf9d/src/defaults/fileIcons.ts#L1708-L1721, you just need to add entries for the `mjs` file extensions to match the existing `cjs` entries.

**Comment by Xenos-the-stupid** [comment]
em i'll do it
