### ISSUE TITLE
postcss icon desappear if the name of the file goes by `postcss.config.{mts,mjs}` (it become either typescript or javascript icon)

### ISSUE THREAD

**Issue by Xenos-the-stupid** [catppuccin/vscode-icons#242]
### VSCode/Codium version

VSCode v1.92.1

### Extension version

v1.14.0

### Describe the bug

if the file name `postcss.config.mts` or `postcss.config.mjs` the file become either typescript icon or javascript icon
![Code_zyC11qnErS](https://github.com/user-attachments/assets/e94d2971-162f-41a6-acfa-8225efa56078)
![Code_HEmUwlnwb8](https://github.com/user-attachments/assets/afb7ca30-e673-4c24-9a3f-c0511552ec3f)

**Comment by uncenter** [comment]
You can keep it open for now, and then add the text `Closes #242` in the body of your pull request. When your pull request is merged, GitHub will automatically close this one!

**Comment by Xenos-the-stupid** [comment]
done thanks
