### ISSUE TITLE
Icon Request: Solidity

### ISSUE THREAD

**Issue by 0xsomerled** [catppuccin/vscode-icons#25]
Hello!

[Solidity](https://soliditylang.org/) is a programming language for developing smart contracts.

It would be nice if there was an icon for files with the `.sol` extension.

Thank you for your time!

**Comment by thang-nm** [comment]
@0xsomerled Would like to try [Catppuccin Perfect Icons](https://github.com/thang-nm/Catppuccin-Perfect-Icons)?

**Comment by prazdevs** [comment]
should be live in the new release ! :)
