### ISSUE TITLE
Icon Request: Http files

### ISSUE THREAD

**Issue by dragove** [catppuccin/vscode-icons#26]
http files are used by some http requests client extensions. e.g. [rest client](https://open-vsx.org/extension/humao/rest-client)  [dothttp](https://open-vsx.org/extension/shivaprasanth/dothttp-code) [httpyac](https://open-vsx.org/extension/anweber/vscode-httpyac)

**Comment by thang-nm** [comment]
@dragove Would like to try [Catppuccin Perfect Icons](https://github.com/thang-nm/Catppuccin-Perfect-Icons)?

**Comment by prazdevs** [comment]
should be live in the new release :)

**Comment by dragove** [comment]
Thanks!
