### ISSUE TITLE
Add icon for benchmarks folder

### ISSUE THREAD

**Issue by scottwillmoore** [catppuccin/vscode-icons#28]
Love this icon pack. Would be awesome to have a custom icon for `bench`, `benchmark`, `benchmarks` directories.

P.S. How are these icons created? Is there a source file for the icons?

**Comment by prazdevs** [comment]
hi, it should be live in the new release :)

I find icons from various open source icon packs (usually using https://icones.js.org ) and redraw them to be 5px wide strokes only, then scripts apply the catppuccin colors :)

**Comment by scottwillmoore** [comment]
Thank you so much!
