### ISSUE TITLE
Add option to disable arrows

### ISSUE THREAD

**Issue by montemartin** [catppuccin/vscode-icons#3]
This is an excellent icon theme, but I find having arrows _and_ folder icons redundant and a bit cluttered. Having an option to disable the arrows (and/or folder icons) would be really nice.

**Comment by zzhaolei** [comment]
I found these references
 - vscode [api](https://code.visualstudio.com/api/extension-guides/file-icon-theme#folder-icons-in-file-icon-themes).
 - material-icon-theme [implementation](https://github.com/PKief/vscode-material-icon-theme/blob/18c992084d11efa461f79aa473fb774d36b440c0/package.json#L225)

**Comment by innocenzi** [comment]
Would love to be able to disable the folder icon 👍

**Comment by prazdevs** [comment]
could be considered whenever we do v1, no ETA at all tho, i'm all over the place atm 😵

**Comment by Alecton4** [comment]
For those who need this feature right now, you can try [this one](https://github.com/thang-nm/Catppuccin-Perfect-Icons#commands). Also, it's pixel perfect, super sharp and clean on my 1080p screen :)

**Comment by prazdevs** [comment]
this was finally added through #79 with new customization features coming soon!

should release under 1.3.0 🎉
