### ISSUE TITLE
 [Icon request] 💨 Tailwind CSS

### ISSUE THREAD

**Issue by GilOliveira** [catppuccin/vscode-icons#33]
Tailwind CSS has the VS Code language identifier `tailwindcss` and it can be manually assigned to CSS files that have this framework's specific syntax.

[Here's their SVG logos.](https://tailwindcss.com/brand)

Thank you :)

**Comment by uynilo9** [comment]
theres already tailwind css?
[https://github.com/catppuccin/vscode-icons/blob/main/icons/tailwind.svg]()

**Comment by prazdevs** [comment]
there is, but the languageId isnt used, i'll add it later :)

**Comment by prazdevs** [comment]
should be live :)
