### ISSUE TITLE
[Icon Request] request add more icons

### ISSUE THREAD

**Issue by zzhaolei** [catppuccin/vscode-icons#36]
`PKief.material-icon-theme` has many icons, but I really like `Catppuccin.catppuccin-vsc-icons`. So I want to be able to add more file and folder icons.
Here is a comparison of the files and folders I used:
<center class="half">
	<img width="170" alt="image" src="https://github.com/catppuccin/vscode-icons/assets/17561793/46c93ff4-eb2f-4d20-b056-4b3bab86ec3f">
	<img width="175" alt="image" src="https://github.com/catppuccin/vscode-icons/assets/17561793/b51189fe-81d6-47d6-99dd-d86fa452e8c8">
</center>

**Comment by prazdevs** [comment]
👋 Hi i can consider adding some new icons and folder icons.
It'd be easier if you list what you think would be good additions :)

**Comment by zzhaolei** [comment]
Here are some icons that I think are interesting:
| prisma | proto | db | error | middleware | app | cmd/cli | auth |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| <img width="50" src="https://www.prisma.io/images/favicon-32x32.png">  | <img width="50" src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/0d8974e6ff26c8ea076d5baa6e6c9e57abb443ba/icons/proto.svg"> | <img width="50" src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/0d8974e6ff26c8ea076d5baa6e6c9e57abb443ba/icons/database.svg"> | <img width="50" src="https://static.thenounproject.com/png/1520745-200.png"> | <img width="50" src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/0d8974e6ff26c8ea076d5baa6e6c9e57abb443ba/icons/folder-middleware.svg"> | <img width="50" src="https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/0d8974e6ff26c8ea076d5baa6e6c9e57abb443ba/icons/folder-app.svg"> | <img width="50" src="https://static.thenounproject.com/png/1876874-200.png"> | <img width="50" src="https://static.thenounproject.com/png/5869853-200.png"> |

**Comment by zzhaolei** [comment]
By the way, prisma’s icon is much smaller than others

<img width="159" alt="image" src="https://github.com/catppuccin/vscode-icons/assets/17561793/b2c7cd51-2e64-47a5-a43e-c8c506831898">

**Comment by prazdevs** [comment]
> By the way, prisma’s icon is much smaller than others
> <img alt="image" width="159" src="https://user-images.githubusercontent.com/17561793/265239694-b2c7cd51-2e64-47a5-a43e-c8c506831898.png">

that's not how it's supposed to look with the theme 🤔 
should look like this
![image](https://github.com/catppuccin/vscode-icons/assets/1631886/dd594f6b-83ab-4e1e-a451-3539818d189b)

**Comment by zzhaolei** [comment]
> that's not how it's supposed to look with the theme 🤔 should look like this ![image](https://user-images.githubusercontent.com/1631886/265773116-dd594f6b-83ab-4e1e-a451-3539818d189b.png)

Try a light theme like `Catppuccin Latte`.

**Comment by prazdevs** [comment]
<img width="129" alt="image" src="https://github.com/catppuccin/vscode-icons/assets/1631886/b80891e5-6879-464a-aa07-0f5dd3f6653c">

you may have something overriding it 🤔

**Comment by zzhaolei** [comment]
I found it, it's affected by the `Prisma.prisma` extension 🤦‍♂️

**Comment by prazdevs** [comment]
some new folder icons will be added in v1 :) (coming soon ™️ )
feel free to reopen a new issue then
