### ISSUE TITLE
[Icon Request] Bun

### ISSUE THREAD

**Issue by eye-wave** [catppuccin/vscode-icons#37]
Bun has recently hit 1.0 and it would be cool to have bun related icons for files like:
- bun.lockb
- bunfig.toml

<img src="https://dashboard.snapcraft.io/site_media/appmedia/2022/07/logo.svg.png" alt="bun logo" width=64>

[Bun website](https://bun.sh)

**Comment by diskomo** [comment]
Hey @eye-wave I added these in here https://github.com/catppuccin/vscode-icons/pull/43

**Comment by prazdevs** [comment]
bun icons are now live :)
