### ISSUE TITLE
[icon request] terraform

### ISSUE THREAD

**Issue by miltlima** [catppuccin/vscode-icons#5]
Hi friends !

First I would like to congratulate you for this theme being really beautiful, if possible I would like to see the icon for terraform.

Thanks!

**Comment by prazdevs** [comment]
i'll work on that when i have some time :)

**Comment by miltlima** [comment]
right , I took the initiative and made one here in vectornator 😁 , I made it in svg , if you want I can send it to you.

**Comment by prazdevs** [comment]
oh i did it and it's already live :)

**Comment by miltlima** [comment]
@prazdevs Thanks, I saw it here, it's great!
