### ISSUE TITLE
[Icon Request] Add support for Helm Chart.lock

### ISSUE THREAD

**Issue by quentinguidee** [catppuccin/vscode-icons#61]
While there is an icon for `.helmignore`, the `Chart.lock` of Helm is not recognized:

<img width="120" alt="image" src="https://github.com/catppuccin/vscode-icons/assets/12123721/0185ee39-7a88-4c8a-a2ea-47e5614a8167">

**Comment by prazdevs** [comment]
closing this, will be available as soon as v1 is published! :)
