### ISSUE TITLE
[Icon Request] drawio files

### ISSUE THREAD

**Issue by xiyaowong** [catppuccin/vscode-icons#62]
Extensions: `drawio` `drawio.svg` `drawio.png` `drawio.html`
Icon: https://github.com/jgraph/drawio/blob/dev/src/main/webapp/images/drawlogo-color.svg

![icon](https://raw.githubusercontent.com/jgraph/drawio/dev/src/main/webapp/images/drawlogo-color.svg)

**Comment by prazdevs** [comment]
will be handled in v1 :) (coming soon ™️ )

**Comment by prazdevs** [comment]
closing this, will be available as soon as v1 is published! :)
