### ISSUE TITLE
[Icon Request] Different Icon for Go Test files

### ISSUE THREAD

**Issue by thelooter** [catppuccin/vscode-icons#71]
It would be nice to have a different Icon for Go test files to easier spot the file on a glance

**Comment by prazdevs** [comment]
If you refer to files named `_test.go` I'm afraid VSCode won't allow that for now, and it's sadly been a while people have been asking for it :/

See https://github.com/microsoft/vscode/issues/12493#issuecomment-1407398244

**Comment by prazdevs** [comment]
closing this for now, since i sadly cant do it. will keep an eye open if VSC ever change their supporter file patterns
