### ISSUE TITLE
Missing PHP icon

### ISSUE THREAD

**Issue by MateuxLucax** [catppuccin/vscode-icons#72]
### Type

- [X] File icon
- [ ] Folder icon

### Context and associations

After the v1.0.0 update, the icon for PHP files are missing. Was this intentional or not?

### References

Before update (v0.33):

<img width="225" alt="image" src="https://github.com/catppuccin/vscode-icons/assets/35275029/e776dee6-3383-4a07-be87-09683c0d0ade">

After update (v1.0.0):

<img width="142" alt="image" src="https://github.com/catppuccin/vscode-icons/assets/35275029/fd3d83ad-ffa1-4fbb-a2c7-24942f8160a5">

**Comment by prazdevs** [comment]
Wasn't intentional, will readd it asap 😄

**Comment by Willy-JL** [comment]
im guessing this is related.

after the update to 1.0.0 2 hours ago, `.c` and `.h` started being drawn by toddlers with crayons:
![image](https://github.com/catppuccin/vscode-icons/assets/49810075/02193483-140c-4376-893e-ff1476a503f4)

previous icons on 0.33.0:
![image](https://github.com/catppuccin/vscode-icons/assets/49810075/1ef33d97-6624-4c0c-ba59-25d20f1398c8)

ill stay on the downgraded version for now

**Comment by prazdevs** [comment]
1. There's a way of saying things. 
2. You may open issues for different icons/requests.
3. Feel free to contribute.

**Comment by Willy-JL** [comment]
> > im guessing this is related.
> > after the update to 1.0.0 2 hours ago, `.c` and `.h` started being drawn by toddlers with crayons: ![image](https://private-user-images.githubusercontent.com/49810075/300123320-02193483-140c-4376-893e-ff1476a503f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMDk0NTgsIm5iZiI6MTcwNjMwOTE1OCwicGF0aCI6Ii80OTgxMDA3NS8zMDAxMjMzMjAtMDIxOTM0ODMtMTQwYy00Mzc2LTg5M2UtZmYxNDc2YTUwM2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDIyNDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiY2RhZWI1YzU2ODdlMGUwMWI3Yzk0YWFmNmZhMDQ3MDA5Y2FlNjg0ZWMyOTA2YjYzZTQ3YWU4ODJiYjJmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1E8bfOZ_4Q8suBLf9KPTzQfQrdQOlXGKKeHza8zGz1I)
> > previous icons on 0.33.0: ![image](https://private-user-images.githubusercontent.com/49810075/300123380-1ef33d97-6624-4c0c-ba59-25d20f1398c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMDk0NTgsIm5iZiI6MTcwNjMwOTE1OCwicGF0aCI6Ii80OTgxMDA3NS8zMDAxMjMzODAtMWVmMzNkOTctNjYyNC00YzBjLWJhNTktMjVkMjBmMTM5OGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDIyNDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2OTFlYzIwN2Y2ODBiZDNmZTM5NTU5MTJhM2Q0MTJhYWZlNDYwMzFjMWYyYmZhOTMzMzMwNjk2ZDdmZDFkZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HT6cVyOVJltcel3PsPwxojkFfuObEjMheT7Y-W-_FhQ)
> > ill stay on the downgraded version for now
> 
> 1. There's a way of saying things.
> 2. You may open issues for different icons/requests.
> 3. Feel free to contribute.

i did not intend to offend anyone, though in hindsight i can see how it couldve been taken that way. i thought this was obviously a mistake and tried to make a joke out of it. so this icon change for .c and .h was intentional?
