### ISSUE TITLE
Did C/C++ header files icon always look like this?

### ISSUE THREAD

**Issue by nyhryan** [catppuccin/vscode-icons#90]
### VSCode/Codium version

1.85.2

### Extension version

1.8.0

### Describe the bug

![image](https://github.com/catppuccin/vscode-icons/assets/85018069/96f96fe3-5573-4f25-8c96-3f7e1b2c3713)
![image](https://github.com/catppuccin/vscode-icons/assets/85018069/477e5991-9827-4990-a1de-e5821114a3ea)

I've just noticed icons for `.h` are bit... large? Have they been always like this or not?

(I'm sorry if this isn't a bug. I couldn't find better place to ask about it)

**Comment by prazdevs** [comment]
Hi, that was a questionnable try on my side, and it's planned to remake them as they look out of place rn. 
They did not look like this before, but I wasn't happy either.

I'll keep this issue open and link it whenever they are reworked! :)
