### ISSUE TITLE
Restore `.yarn/` folder icon

### ISSUE THREAD

**Issue by nekowinston** [catppuccin/vscode-icons#97]
### Type

- [x] File icon
- [X] Folder icon

### Context and associations

Somewhere along the way, we regressed on #59
- `.yarn/`
- `yarn.config.cjs`

**And we're using the old yarn v1 logo again.**

### References

As in the previous PR

**Comment by prazdevs** [comment]
will spend some time this weekend to make all the icons currently required 😄
